Add parallel_scan exercise
kokkos/kokkos-tutorials pull request #87
Opened 2024-04-23 15:56 UTC by masterleinad

2024-04-23 21:36 UTC, dalg24 commented on Exercises/parallel_scan/Solution/parallel_scan.cpp
> +  KOKKOS_FUNCTION void operator()(int i, value_type &update,
maybe update -> partial_product

2024-04-23 21:36 UTC, dalg24 commented on Exercises/parallel_scan/Solution/parallel_scan.cpp
> +#include <cstdio>
You need to include `<iostream>`
I expect this does not compile with 4.3

2024-04-23 21:36 UTC, dalg24 commented on Exercises/parallel_scan/Begin/parallel_scan.cpp
> +  /* FIXME */
Didn't we commonly use EXERCISE to mark places that needed to be edited?

2024-04-25 14:32 UTC, crtrott requested changes
Two mistakes: did you try this with GPU?

2024-04-25 14:32 UTC, crtrott commented on Exercises/parallel_scan/Begin/parallel_scan.cpp
> +    Kokkos::View<double *> reference_view("reference", n);
```suggestion
    Kokkos::View<double *, Kokkos::HostSpace> reference_view("reference", n);
```

2024-04-25 14:32 UTC, crtrott commented on Exercises/parallel_scan/Solution/parallel_scan.cpp
> +    Kokkos::View<double *> reference_view("reference", n);
```suggestion
    Kokkos::View<double *, Kokkos::HostSpace> reference_view("reference", n);
```

2024-04-25 15:14 UTC, merged